version: 2

builds:
  - main: ./cmd/ljp/
    binary: ljp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
